import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import '../models/content_meta.dart';

/// Loads the pre-built content index:
///   assets/build/content_index.json
///
/// This JSON is generated by tools/encrypt_content.dart and contains
/// metadata + relative paths to .md.enc assets.
Future<List<ContentMeta>> loadContentIndex() async {
  final jsonStr = await rootBundle.loadString(
    'assets/build/content_index.json',
  );

  final decoded = jsonDecode(jsonStr) as List<dynamic>;
  final result = <ContentMeta>[];

  for (final item in decoded) {
    final map = item as Map<String, dynamic>;

    // Optional: only use English entries for now
    final lang = map['lang']?.toString();
    if (lang != null && lang != 'en') continue;

    result.add(ContentMeta.fromJson(map));
  }

  // Stable ordering: newest date first (fallback to 1970 if null)
  result.sort((a, b) {
    final ad = a.date ?? DateTime(1970);
    final bd = b.date ?? DateTime(1970);
    return bd.compareTo(ad);
  });

  return result;
}
