class ContentMeta {
  final String title;
  final String slug;
  // page | project | blog | lab | library | meta | foundation | timeline ...
  final String type;
  final String visibility; // public | private
  final DateTime? date;
  final String summary;
  final List<String> tags;
  final String? thumbnail;
  final String path; // asset path, now pointing to .md.enc
  final String? readingTime;

  const ContentMeta({
    required this.title,
    required this.slug,
    required this.type,
    required this.visibility,
    required this.date,
    required this.summary,
    required this.tags,
    required this.thumbnail,
    required this.path,
    this.readingTime,
  });

  bool get isPrivate => visibility.toLowerCase() == 'private';
  bool get isPublic => visibility.toLowerCase() != 'private';

  /// Construct from the JSON generated by tools/encrypt_content.dart
  factory ContentMeta.fromJson(Map<String, dynamic> json) {
    DateTime? dt;
    final ds = (json['date']?.toString() ?? '').trim();
    if (ds.isNotEmpty) {
      dt = DateTime.tryParse(ds);
    }

    final tagsJson = json['tags'];
    final tags = <String>[];
    if (tagsJson is List) {
      tags.addAll(tagsJson.map((e) => e.toString()));
    }

    // encrypt_content.dart writes relative paths like:
    //   "en/blog/calm-technology.md.enc"
    final rawPath = (json['path']?.toString() ?? '').trim();
    final fullPath = rawPath.startsWith('assets/')
        ? rawPath
        : 'assets/contents/$rawPath';

    return ContentMeta(
      title: (json['title'] ?? '').toString(),
      slug: (json['slug'] ?? '').toString(),
      type: (json['type'] ?? 'page').toString(),
      visibility: (json['visibility'] ?? 'public').toString(),
      date: dt,
      summary: (json['summary'] ?? '').toString(),
      tags: tags,
      thumbnail: json['thumbnail']?.toString(),
      path: fullPath,
      readingTime: json['reading_time']?.toString(),
    );
  }
}
